version: '3'
services:
  rpc:
    image: ethereum/client-go:alltools-v1.10.20
    volumes:
      - ./chain:/home/chain
      - ./.ethereum:/root/.ethereum
    ports:
      - "30305:30305"
      - "8545:8545"
      - "8546:8546"
    restart: always
    entrypoint: geth --datadir /home/chain/rpc --networkid 8549140784658 --port 30305 --bootnodes "enr:-KO4QMMxjBZ4mZlyP7G841dsCqrnLexbcQDo2ytNNdMzaBswTpBIHhwGZ3ERptHT7H9MipduQcAGHXEB4SL4zYk0EKOGAYIHp3aDg2V0aMfGhDdAgD2AgmlkgnY0gmlwhMCoH_yJc2VjcDI1NmsxoQNPBYcxtMwrRkan0ORifbBO47NMEHiWo0xNu1da14WfvoRzbmFwwIN0Y3CCdl-DdWRwgnZf" --http --http.api personal,eth,net,web3 --http.corsdomain '*' --http.addr 0.0.0.0  --ws --ws.api eth,net,web3 --ws.origins "*" --ws.addr 0.0.0.0  --syncmode full