version: '3'
services:
  rpc:
    image: ethereum/client-go:alltools-v1.10.20
    volumes:
      - ./chain:/home/chain
      - ./.ethereum:/root/.ethereum
    ports:
      - "30305:30305"
      - "8545:8545"
      - "8546:8546"
    restart: always
    entrypoint: geth --datadir /home/chain/rpc --networkid 8549140784658 --port 30305 --bootnodes "enr:-KO4QDa8h16x-O1NTU1DBB-CvAIAOxG7mgo1bhjl6EUcAR8-CJVpl651trm9Nirlk9iyhf1U4LA0SPa-xTDYb4dor7mGAYIPdIy2g2V0aMfGhONvYk-AgmlkgnY0gmlwhMCo9haJc2VjcDI1NmsxoQKvsdGQw3kmXU4KV5T_SBCOOq85B1-PvmFroTmh1IIbi4RzbmFwwIN0Y3CCdl-DdWRwgnZf" --http --http.api personal,eth,net,web3 --http.corsdomain '*' --http.addr 0.0.0.0  --ws --ws.api eth,net,web3 --ws.origins "*" --ws.addr 0.0.0.0  --syncmode full