version: '3'
services:
  ipfs:
    image: golang:1.15.15
    volumes:
      - ./chain/ipfs:/home/chain/ipfs
    working_dir: /home/chain/ipfs
    command: /bin/bash -c "go get -u github.com/Kubuxu/go-ipfs-swarm-key-gen/ipfs-swarm-key-gen && ipfs-swarm-key-gen > /home/chain/ipfs/node1/data/swarm.key"