version: '3'
services:
  miner:
    image: ethereum/client-go:alltools-v1.10.20
    volumes:
      - ./chain:/home/chain
      - ./.ethereum:/root/.ethereum
    ports:
      - "30307:30307"
    restart: always
    entrypoint: geth --datadir /home/chain/miner --networkid 8549140784658 --port 30307 --bootnodes "enr:-KO4QMMxjBZ4mZlyP7G841dsCqrnLexbcQDo2ytNNdMzaBswTpBIHhwGZ3ERptHT7H9MipduQcAGHXEB4SL4zYk0EKOGAYIHp3aDg2V0aMfGhDdAgD2AgmlkgnY0gmlwhMCoH_yJc2VjcDI1NmsxoQNPBYcxtMwrRkan0ORifbBO47NMEHiWo0xNu1da14WfvoRzbmFwwIN0Y3CCdl-DdWRwgnZf" --unlock 0x4432047680544F439f269fBAf47997Ac6594B03c --mine --keystore /home/chain/account/keystore --password /home/chain/password  --miner.threads 1